// apps/client2/src/components/index/CreateColorButton.svelte
<script lang="ts">
  import { getRandomColor } from '../../api';
  import { color } from '../../store';

  const getColor = async () => {
    const { data: newColor } = await getRandomColor();
    color.set(newColor);
  };
</script>

<div class="flex justify-center">
  <button
    class="bg-gray-300 text-xl rounded-full p-4 shadow-md shadow-grey-200 hover:shadow-lg hover:shadow-grey-300 w-4/12"
    on:click={() => getColor()}
  >
    Generate color
  </button>
</div>

// apps/client/components/CreateColorButton.tsx
import { Button } from 'evergreen-ui';
import { useQuery } from 'react-query';
import { getRandomColor } from '../api';

const CreateColorButton = () => {
  const { data: newColor } = useQuery('newColor', getRandomColor);

  const handleClick = () => {
    console.log('clg', newColor);
  };

  return (
    <>
      <style jsx>{`
        div {
          display: flex;
          justify-content: center;
          margin: 6rem 0;
        }
      `}</style>
      <div>
        <Button appearance='primary' onClick={handleClick}>
          Generate color
        </Button>
      </div>
    </>
  );
};

export default CreateColorButton;
